
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { Principal } from './componentes/Principal.jsx'
import "./estilos.css"
import { Respuesta } from './componentes/Respuesta.jsx'
createRoot(document.getElementById('root')).render(
  
  <StrictMode>
    <h1>Si esos infelices piensan que se las voy a dejar fácil están en un error sin precedentes</h1>
    <br />
    <Respuesta/>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
    <Respuesta></Respuesta>
  </StrictMode>,
)
